language: php
php:
- '7.0'
script:
- true
before_deploy:
- git remote add pantheon $PANTHEON_REMOTE
- git remote add github git@github.com:$TRAVIS_REPO_SLUG
- openssl aes-256-cbc -K $encrypted_e9bba95f5f6f_key -iv $encrypted_e9bba95f5f6f_iv
  -in scripts-ci/test-ci.enc -out $HOME/.ssh/id_rsa -d
- chmod 0600 $HOME/.ssh/id_rsa
- openssl aes-256-cbc -K $encrypted_1655b4514240_key -iv $encrypted_1655b4514240_iv
  -in scripts-ci/host.enc -out $HOME/.ssh/host -d
- cat $HOME/.ssh/host >> $HOME/.ssh/known_hosts
deploy:
- provider: script
  script: scripts-ci/code-sync.sh
  on:
    branch: master
after_deploy:
- composer global require "hirak/prestissimo:^0.3"
- /usr/bin/env COMPOSER_BIN_DIR=$HOME/bin composer --working-dir=$HOME require pantheon-systems/terminus
  "<0.13.0"
- "/usr/bin/env COMPOSER_BIN_DIR=$HOME/bin composer --working-dir=$HOME require drush/drush:8.*"
- composer install
- terminus auth login --machine-token=$TERMINUS_TOKEN
- terminus aliases
- drush $PANTHEON_SITE_ENV cr
env:
  global:
  - secure: mp3ZIRdce9fSPh1ywePimJ+3d/QlpGTz1PIPCXhIK++S2q58shD5jypF5GCDaKitTUnptesGI8+Rv5zpI76oN1uT5qDtMpmsXYxPrVCgKdwgHEkyzQEsPfoWWRWp2ygOMJf0V3ZmDhwV4pm07Lxc+5bggZR8kn8tjrNC2IRA5g/3HppupSjBerjnZKYZJRYgQwRL9bzxWQRauaCUes2zxRND7GpFfPj9psHHpe1b5X7xRSh+EWltO5FJ+/TGKTy3VM54OSBArsqTwbgTQvKn01/okittBNcrn1Bew3+5lD01gvJgO9BkqrPJA6oloFBE4waUJQjJYaPyfO5XILJ/fF8fnw/uumwX/w/iDYiSaCHeYWo2HQZnL3u0LT5lr6RmRzoygVgGyFybEHpuk8onXPS3C1+nh4NqdgFdoiQrXXUPVcV8SFWTYkD6s7XqkFduuEclYP7vPZKxUlKzCNtWyt/qoeY/OsJ1ZD5I5x6TKMEV8P+GKtWUqXAlQqU00Tm7/5FppuqMesR8ULuexrQ09h+T0/Cg5rKSXaZ4xccbUYPQPjm78MeShbIYORCdgsDfjob+Y+ZbSCJuDBQP+xEGQXaMFngGu+vntjFLjfmWVi0cOpZXFCf2xRMGKh152OEG90JqHNx2xQiyLeH5JtzdwPvYh5262dUv6C4Pjj0cmhw=
  - secure: S0EyjqFkRO5nTuWq/YCmRooclGLajkc6kAhKqM0UMbR0xDYbwLf3oKKA5sPzqw4vzguEZDRvFjyZFfyWxdZ7Wf0GD/N25U76ztqRilQUBJL3oo4w9TuyLBz4DLlxn15agim/gUX+RxWEPFQn8QXfR7VIi/OHP2KU3U4pS8q6+trinXlthHRMCGJnhN8hbOwDKvjtSZBrNOrQXQwHJNzIB4b04U29fLqG5jNBKz7xRwmvsSXErdekiQCDoqcGoZmI3GunssZr1+avuXq91RwHfADm5DSEJOxew+CkJVgPLn4jU4s918FgzaEk7pbZ8vICkODVVfxB59YoSxXlOsh3EVR+eAFqTz0DlxChD+WTICfDgHi/A6IiOXNZbITnWTO48nkL5xJ11fHSewC3EFbLCxfB3+btqHM6kE0/uNMKC0X98I7Tihl0hkJWDKlFhrfLJfFvhKcgk3MQUVTXDS31hCjZ32EGeSGa+twNQhz8UkRsdYjIT5LSBEikKAp1vPwuN/H4DyrDnnStBbvJkxMq1+4GRO7bFBptSqg/7eG61+bNAn59hhStKrkt43tNmyk9uCUoWhN4ne8BAee/rDdyHR8me+i5LAZBD4mO9DMkvxEzsw6oN1EKxOZzUsDrJRd+bUPVgSs8wOu/KXqCSMWdFUH+6ZO89Yb11/NEjrxWCLo=
  - secure: bCVPcZt/c0Y9FoRNMTW3JDklne9Qrb5mw+WxjVCYCbvSxoDuE1POvwo1lMbrP8RnpDXvt9tmvvOLyJjdNHAIPZIqSMPAbYpVti6OjFkIHJmMMZSPEwRa0QkBJIvqQk5FXuz2nBJfL4eEIPrH4Ge6igfsqPlmKEWe+3XAaGuh+FPm1BYYeOwwcroSw2mexNdYycr+K4unhS1vNGvktl/c9mUfjcz2zRTDyVVYatoKUPh+z7275uIBXxz2fIjInyubwx3jGJVnkHfFeNsNtmCTZhH66uV9H0mgPehVwgOWawhdPovIdmAg/9f7SoVCOhoZDKSD97qc3f3s/58XCCkSI6xKuhgtySf9ltTNQlEXaYM2kRCaf9FCFZ0ZmOkeFHgN0Eo7eM+k+DjmToxz23E6xfNwur6z3+U3ZEblqbEzLzDFkLpHSyX1hgWeSzenXJnvoWdpR0Nb0SRnnLNwz52UgJjbjo27nyTTNx/FW9vd6efaDIRcBcV1en6K3f71w7VccMG5mw0KHiJwxZD8H5IiXAU4bs8XZ/EhnLnF6ufoavOuO0KPrS0O3zP+k8YUwSLtwxbQaz0Q4CwZ9RC8k1W2hqu5n/qc8cpw96wes5tUf55X8GVZKgwwyHlzQ5xlcz/HxEcRY3TXjUDcUEnah84S6mM4tipU9N+wpTePnhxSRnI=
